### ISSUE TITLE
Add JSDoc comments to functions

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#130]
This SDK has many functions that don't have comments, making the code more difficult to understand. Sometimes the comments don't make sense or have spelling errors.

Ideally we add comments to the functions.

Example: `receiver_structured.js`

**Comment by lance** [comment]
I agree - JSDoc is super important. Ideally, I'd like to work to narrow and simplify the exposed API so that we can know best how to prioritize effort when documenting functions. Maybe we can start with the `CloudEvent` and `HTTPReceiver` classes, since those are the most accessible/easiest to use parts of the API at the moment.

**Comment by lance** [comment]
Now that we have JSDoc everywhere and are [publishing it](https://cloudevents.github.io/sdk-javascript/), this can be closed.
