### ISSUE TITLE
Receiver accept() method modifies its input parameter.

### ISSUE THREAD

**Issue by matejvasek** [cloudevents/sdk-javascript#230]
The receiver may destroy input payload.
For instance after calling `receiver.accept(response.headers, response.data)` the data member may end up as empty object. 

https://github.com/cloudevents/sdk-javascript/blob/fba3294ce04a30be0e5ab551a1fa01727dc8d1f8/src/lib/bindings/http/validation/structured.js

**Comment by lholmquist** [comment]
I'm not totally following from the link you posted.   Would it be possible to post a small code example of what you are seeing?

**Comment by lance** [comment]
@lholmquist the issue is here: https://github.com/cloudevents/sdk-javascript/blob/fba3294ce04a30be0e5ab551a1fa01727dc8d1f8/src/lib/bindings/http/validation/structured.js#L38. Even though the `payload` is assumed to be transformed by the parser [here][(https://github.com/cloudevents/sdk-javascript/blob/fba3294ce04a30be0e5ab551a1fa01727dc8d1f8/src/lib/bindings/http/validation/structured.js#L29) the parser in many cases is a "pass through" parser - doing nothing but returning the parameter. So we end up with the caller's `payload` object being modified.

**Comment by lholmquist** [comment]
ah,  ok.  sounds like a bug

**Comment by matejvasek** [comment]
@lance @lholmquist  note that I reproduced this on the Lance's TS rework branch, I am going to try to reproduce this on master.

**Comment by matejvasek** [comment]
Yes, the "pass through" parser causes problem.

**Comment by matejvasek** [comment]
I would submit PR, but I won't since @lance is going to rewrite a lot of things.
