### ISSUE TITLE
Immutable event builder

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/sdk-javascript#29]
Implements an immutable event builder, to builds events instances that are unchangeable after its build.

Depends on #28

**Comment by lance** [comment]
@fabiojose I agree that events should probably be immutable - aside from a well-defined path for converting from/to spec versions. Given how the repo has been evolving, how do you think this issue should progress?

**Comment by grant** [comment]
> how do you think this issue should progress?

If we use JSON for CloudEvents, then we can just `Object.freeze` our event data to make it immutable.

Requires https://github.com/cloudevents/sdk-javascript/issues/65.

**Comment by lance** [comment]
I'm going to mark this a stalled for now. TypeScript users now have `Object.freeze` for regular objects. However, that doesn't work for the `CloudEvent` class. We'd need to add a `freeze()` method to the class itself to prevent modification. This is because the setters on the class [delegate to `this.spec`](https://github.com/cloudevents/sdk-javascript/blob/master/src/lib/cloudevent.ts#L109-L111).

**Comment by grant** [comment]
Marking all `CloudEvent` fields as `readonly` should be a solution.

This is very common and recommended in TypeScript. See vscode's source for examples.

**Comment by lance** [comment]
Weird that the bot closed this

**Comment by lance** [comment]
While not exposed via an actual _builder_, I think https://github.com/cloudevents/sdk-javascript/pull/234 should satisfy this issue. Closing.
