### ISSUE TITLE
Adding More Transport Protocols - A Proposal

### ISSUE THREAD

**Issue by lholmquist** [cloudevents/sdk-javascript#322]
**What follows is a thought dump, so sorry if it rambles a bit.**

This module is in a pretty good state with the HTTP Protocol, so i started thinking about what the next protocol that could be added.

As I thought about it,  I realized a couple things.  

This first is we probably need to make our top level `Receiver` and `Emitter` a little more generic.  At the moment,  they have things related to the HTTP Protocol in them.

This second thins is when we add a new transport protocol in, we are also potentially going to increase the dependencies for each one added.  My assumption would be that we would use a library related to that transport protocol for emitting events.  For example,  if we added MQTT then we might use the [mqtt](https://github.com/mqttjs/MQTT.js) module.

The problem,  and maybe it isn't a problem, is that a user might only want or need 1 protocol,  and if we had multiple protocols implemented,  then they would be getting more dependencies than needed.

One solution to this could be creating new modules that depend on this module as a base for each of the new Protocols.   I would assume we would just keep the HTTP protocol in the base module since, and i have no data to back this up, it might the most common to use.  So if a user wanted the MQTT protocol, they could just install that module.  However; if they wanted to use multiple protocols,  I could see this becoming a little messy.

Another solution i thought about was some sort of plugin architecture,  but i not really sure of the UX of it. with this case we would still be creating separate modules to plugin,  but there would be one "entry point" to creating new Emitters and Receivers

Again,  this was a thought dump to start a discussion on our best path forward.

**Comment by lholmquist** [comment]
@cloudevents/sdk-javascript-maintainers and anyone else

**Comment by lance** [comment]
@lholmquist thanks for bringing this up! As you know, I'm interested in moving ahead with MQTT protocol support in the near future.

One thing to consider is that we don't really need to support the MQTT protocol itself, we just need to provide a means for developers to [express a `CloudEvent` as an MQTT publish message](https://github.com/cloudevents/spec/blob/v1.0/mqtt-protocol-binding.md#12-relation-to-mqtt). In fact, I would say with regard to HTTP, our choice to use Axios to send over the wire may not actually be the best thing. The module could be smaller and more concise if we simply provided methods similar to this.

```js
// send a cloud event
const ce = new CloudEvent({ /** attributes */ });
const structuredHTTPMessage = HTTP.asStructured(ce);

// then it's up to the developer to actually send these using whatever HTTP module they like
axios.request( {
  method: POST,
  data: structuredHTTPMessage.body,
  headers: structuredHTTPMessage.headers
});

// receive a cloud event using express
app.post('/', (req, res) => {
  const incomingEvent = HTTP.receive(req.headers, req.body);
});
```
In fact, that's essentially how our `Receiver` works today. It doesn't really know about the HTTP protocol itself - it just accepts some headers and a body. It's a little strange to me that we do it so differently by actually sending an event over the wire when emitting an event.

I say all of this to emphasize that we don't really need to worry about the MQTT protocol. We just need to provide a way to transform a `CloudEvent` instance into an MQTT publish message, and to read an MQTT publish message and convert it into an event. This is good, because the `mqtt` module is not small. Including all of its dependencies, it runs about 10MB.

**Comment by lholmquist** [comment]
>  It's a little strange to me that we do it so differently by actually sending an event over the wire when emitting an event.

One reason i can see having an Emitter, is to make the users life a little easier with not having to worry about setting the correct method and those other tiny details.    But I think that making this library smaller,  and focused on just formatting(receieving and sending) the CloudEvents might be a good direction to go in 


That would allow a user to use their http lib of choice(or other protocol lib of choice).

This would also solve the issue #314 about the Emitter being static,  since we wouldn't have an emitter function anymore
