### ISSUE TITLE
Should throw if specversion attribute is missing

### ISSUE THREAD

**Issue by satazor** [cloudevents/sdk-javascript#332]
**Describe the Bug**

Does not throw if event doesn't have a `specversion` attribute, and fallbacks to `1.0`. The spec says that the `specversion` attribute is mandatory, so I think this library should fail when it's missing, instead of "magically" falling back.

**Steps to Reproduce**
1. `Receiver.accept({ 'Content-Type': 'application/cloudevents+json' }, { id: 'foo', source: 'foo', type: 'foo' });`
2. Prints `console.error` saying it will fallback to `1.0`
3. Validation passes

**Expected Behavior**
It should throw, since the `specversion` attribute is missing

**Comment by satazor** [comment]
https://runkit.com/embed/chsthvg529ba

**Comment by lance** [comment]
@satazor thanks for pointing this out. I will look into dealing with this in https://github.com/cloudevents/sdk-javascript/pull/328

**Comment by lance** [comment]
@satazor in [this PR](https://github.com/cloudevents/sdk-javascript/pull/328), there was [discussion](https://github.com/cloudevents/sdk-javascript/pull/328#issuecomment-682059664) around loose validation on receipt of a `CloudEvent`. Based on input from the community, noted in that comment, receipt of a `CloudEvent` should have loose validation, since it should be possible to receive and recover from poorly formed/invalid events. The example you provide is when receiving events on the wire - just such a scenario. If you would like to check whether the received event is valid, you can call [`CloudEvent#validate()`](https://cloudevents.github.io/sdk-javascript/classes/cloudevent.html#validate). 

That method returns a `boolean`. I think it might be nice to see what the validation errors actually were, and we don't really have a convenience function for that. In any case, this is expected behavior.

**Comment by lance** [comment]
Oh - but I see the problem here. Since it's defaulting the `specversion`, property, by the time it's unmarshalled as a `CloudEvent`, it _is_ valid, so calling `ce.validate()` won't help.

**Comment by lance** [comment]
The other required attribute that we supply a default for if it's not provided is [`id`](https://github.com/cloudevents/sdk-javascript/blob/7423acb7fc4d431cc8d335fd5ccb1ad4a1f28a65/src/event/cloudevent.ts#L54-L55). The same would happen for this.

**Comment by lholmquist** [comment]
I know this has been open for a while, but the idea is that we shouldn't be defaulting the specversion and id fields?

This would be a good one to get into the 4.0 release.  i can assign myself to take of it

**Comment by lance** [comment]
> I know this has been open for a while, but the idea is that we shouldn't be defaulting the specversion and id fields?

I think defaulting them on creation with `new CloudEvent()` is fine. But when receiving events, we should not just assume that they are v1.0. That's what we are doing here.

https://github.com/cloudevents/sdk-javascript/blob/f6be285b8319919029d8c11f7bb49cac4bcc5c14/src/message/http/index.ts#L58-L60

Throwing here would also remove that `console.error()` and resolve https://github.com/cloudevents/sdk-javascript/issues/333

**Comment by lholmquist** [comment]
@lance that sounds good.   i'll take of it

**Comment by c-pius** [comment]
> I think defaulting them on creation with new CloudEvent() is fine. But when receiving events, we should not just assume that they are v1.0. That's what we are doing here.

I think this should also be the same for the `id` attribute, right?

As of now, `HTTP.toEvent()` will also assign a new uuidv4 to an event if passed in `structured` mode with no `id` present. This time even implicitly without a log message that it was defaulted.

---

`parseStructured` will call the CloudEvent constructor with `eventObj` missing the `id` attribute and generate it.
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L231 
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/event/cloudevent.ts#L61

---

PS: the same would also happen with the `time` attribute. Maybe less important though because not a required attribute.

**Comment by c-pius** [comment]
FYI, there is another effect that when calling `HTTP.toEvent` with a structured mode event and a `specversion` value different from `1.0` or `0.3` (e.g. `2`), than the defaulting here is applied:
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L58

but the parsed event is actually getting the original value (e.g. `2`) assigned by this block:
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L208

---

in binary mode this is prevented by this block:
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L129

no sure if therefore this block for structured should use the body attributes instead (I think sending ce-header even though structured mode is used is valid as long as the context attributes are present in the body)?
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L189

**Comment by lance** [comment]
@lholmquist ping - were you still thinking you'd take this? If not, I'll pick it up. Running into this as an issue now with function runtime.

**Comment by lholmquist** [comment]
@lance it isn't on my radar atm,  so feel free to pick it up
